#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in8,    towerPot,       sensorPotentiometer)
#pragma config(Sensor, dgtl1,  topButton,      sensorTouch)
#pragma config(Sensor, dgtl2,  ultrasonic,     sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port9,           towerMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Includes
#include "DriveBase.c"

// Prototypes
void cleanup();
void waitForButton();
void testEncoders();

// Code
task main()
{
	clearDebugStream();
	wait1Msec(250);

	while(SensorValue[towerPot] < 4095) {
		motor[towerMotor] = 30;
		if(SensorValue[towerPot] < 100) {
			break;
		}
		writeDebugStreamLine("Value: %d", SensorValue[towerPot]);
	}

	motor[towerMotor] = 0;

	//waitForButton();

	//wait1Msec(400);

	//driveInit();
	//arcTurn(20, 70, false, 10, 0);
	//driveInit();
	//arcTurn(20, 100, true, 10, 0);
	//driveInit();
	//arcTurn(20, 100, false, 10, 0);
	//driveInit();
	//arcTurn(20, 70, true, 10, 0);

	cleanup();
}

// General cleanup and safety code
void cleanup()
{
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(leftMotor);
}

void testEncoders() {
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(leftMotor);

	while(true)
	{
		waitForButton();

		resetMotorEncoder(rightMotor);
		resetMotorEncoder(leftMotor);

		for(int i = 0; i < 1000; i++)
		{
			motor[leftMotor] = 70;
			motor[rightMotor] = 70;

			writeDebugStreamLine("Left: %d", getMotorEncoder(leftMotor));
			writeDebugStreamLine("Right: %d", getMotorEncoder(rightMotor));

			wait1Msec(1);
		}

		cleanup();
	}
}

void waitForButton() {
	while(!SensorValue(topButton)) {
		wait1Msec(5);
	}
}
